spring:
  application:
    name: weather-api
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:qwert}
  flyway:
    enabled: true

weather-api-keys:
  yandex: ${WEATHER_YANDEX_KEY}
  apiNinjas: ${WEATHER_NINJAS_KEY}
  openweathermap: ${WEATHER_OPENWEATHERMAP_KEY}

weather-api-settings:
  call-interval: 300000
  initial-delay: 50000

locations:
  countries:
    Russia:
      - city: Moscow
        lat: 55.7558
        lon: 37.6176
      - city: Saint Petersburg
        lat: 59.9343
        lon: 30.3351
      - city: Novosibirsk
        lat: 55.0084
        lon: 82.9357
    Germany:
      - city: Berlin
        lat: 52.5200
        lon: 13.4050
      - city: Hamburg
        lat: 53.5511
        lon: 9.9937
    China:
      - city: Beijing
        lat: 39.9042
        lon: 116.4074
      - city: Shanghai
        lat: 31.2304
        lon: 121.4737
    Japan:
      - city: Tokyo
        lat: 35.6895
        lon: 139.6917
      - city: Osaka
        lat: 34.6937
        lon: 135.5023
    USA:
      - city: New York
        lat: 40.7128
        lon: -74.0060
      - city: Los Angeles
        lat: 34.0522
        lon: -118.2437
